name: 'deploy'

on:
  release:
    types:
      - published
  push:
    branches:
      - dev
      - main
  workflow_dispatch:
    - test
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 'deploy'

    steps:
      - uses: actions/checkout@v3
      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          vercel-args: '--scope=thebaodev' # change this to your project scope
          scope: ${{ secrets.VERCEL_ORG_ID }}
          alias-domains: |
            typesth.vercel.app
